### ISSUE TITLE
Plugin immediately crashes when request is made against the port

### ISSUE THREAD

**Issue by jostmart** [rabbitmq/rabbitmq-prometheus#43] opened 2020-05-15 16:11 UTC
## Facts

Upgrade done today on Erlang. With a following reboot. RabbitMQ is clustered, cluster status OK.

```
# grep "May 15" /var/log/yum.log
May 15 11:18:21 Updated: erlang-23.0-1.el7.x86_64
```

Installed active and inactive plugins
```
sudo rabbitmq-plugins list | grep -i "\[e"
[E*] rabbitmq_management               3.8.3
[e*] rabbitmq_management_agent         3.8.3
[E*] rabbitmq_prometheus               3.8.3
[e*] rabbitmq_web_dispatch             3.8.3
```

## Installed packages
erlang.x86_64                          23.0-1.el7                      @rabbitmq_erlang
rabbitmq-server.noarch                 3.8.3-1.el7                     @/rabbitmq-server-3.8.3-1.el7.noarch

Plugin listening on 15692
```
netstat -lnpt | grep 156
tcp        0      0 0.0.0.0:15692           0.0.0.0:*               LISTEN      1150/beam.smp
tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      1150/beam.smp
```

Using curl, causes a crash.
```
$ curl -v -H "Accept:text/plain" "http://localhost:15692/metrics"
* About to connect() to localhost port 15692 (#0)
*   Trying ::1...
* Förbindelse vägras
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 15692 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:15692
> Accept:text/plain
>
< HTTP/1.1 500 Internal Server Error
< content-length: 0
<
* Connection #0 to host localhost left intact

```

Log segment from the crash
```

2020-05-15 18:03:16.573 [error] <0.10987.3> CRASH REPORT Process <0.10987.3> with 0 neighbours crashed with reason: {badarg,[]}
2020-05-15 18:03:16.573 [error] <0.10986.3> Ranch listener rabbit_web_dispatch_sup_15692, connection process <0.10986.3>, stream 1 had its request process <0.10987.3> exit with reason badarg and stacktrace []
```

**Comment by michaelklishin** [comment] 2020-05-15 18:18
Duplicate of #42. Erlang 23 is [not supported at the moment](https://twitter.com/RabbitMQ/status/1260555039858442241).

**Closed by michaelklishin** 2020-05-15 18:18 UTC
